artifactory-server: https://renodesorenterprise.jfrog.io/artifactory
artifactory-username: "renodesor@yahoo.fr"
artifactory-password: "D&sormeau1jf"
artifactory-api_key: da269b86-62ae-4987-92ab-a3863a400735
artifactory-access-token: eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJvYU1PcjJnUFUtNTFuMTRtNWZLQ1lpSUFUNlppaHFQbWtNLTRMemJuSU00In0.eyJzdWIiOiJqZmZlQDAxZ3Q3NWtlanA3a3JtMGZkZ2pka3ExeTN5XC91c2Vyc1wvcmVub2Rlc29yQHlhaG9vLmZyIiwic2NwIjoic3lzdGVtOmlkZW50aXRpZXM6cix3LGQiLCJhdWQiOiJqZmFjQCoiLCJpc3MiOiJqZmZlQDAxZ3Q3NWtlanA3a3JtMGZkZ2pka3ExeTN5IiwiaWF0IjoxNjc3NTQ5NjQxLCJqdGkiOiI2MTNkYzk1OC1jZGI0LTQxZTItOWEwYi1kMzcwNzliZDVjY2IifQ.a9G8tkkT0dc0v9LHVAzSCepVQhVU1qbL12pbyqKTKZeNuFnNqpkmkMzhVMFHBLuiwa9gI03jerjzsi2hMlyjPysQNt0vNLJ0hbdzqG1z0uCHdi5LXIshUz_nEAak2NgJphISyMKKjQK0B1pQMXICI2BDnKJqQyBoqUTwwJdTNRM71K5Wdb649MxwtAVT-EKLXUeeh1llhAV1Ekj2bGJjk2t--mwZ4WwDqe6oV0HhzVeT9xXDWGLFN3WfoDVfKcYScEiTivRuzxiMGyal5nUrIuIGGfwFlnqPq1xfi1gc_UWWeJZmH8whqVI0Z-O_B0gh2I1p7BTTOoHi7Ru8elOIUA

#BUILD_TEAM_NAME: main
#BUILD_PIPELINE_NUMBER: spring-security-auth
#BUILD_PIPELINE_NAME: spring-security-auth
#BUILD_JOB_NAME: build
#BUILD_NAME: 1.2.3
#BUILD_ID: 1.2.3
#COMPONENT_NAME: SpringSecurityAuth
#MAVEN_ADDITIONAL_ARGS: -Dpackage=war
PRODUCT_NAME: com/renodesor/multimodule
artifactId: gs-multi-module
git-repo-url: https://github.com/renodesor/gs-multi-module.git
private_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
  NhAAAAAwEAAQAAAYEAot3exQY7g0EoQoNKmZLe4SMiktD0rJYVouKed/TdsyBpoH3+r+u7
  3mrJ4mQSCDk6BGkq+GvG6J3dSDY9cbODRBuydoDoGpFd+Pg6s6UfP14lANLBl1Crc0/WND
  cxsNg0OiMkuMOoAzfZvFRjQxKkx4jkffLy525sZGXskzFFeBOEXvfVKClA2nUaAPqnvy1i
  fh95icAdH7rMxRdCxmWXdtyihyCxvmnJyqTbiNGyqD4Y5YgVGaAj34GmQf77vDD3t706gv
  98cmGSmXn8xWymUgFEwdC10IPg45YQH1o57hZRuhr1P651I0J4ZieIO3hnoGqHKdWxq/iW
  ODW49MxSwj/XgpXVly9ofYtsftByHKqr1SALzf0aOptL0PTP+KLF0FrFVU8PtAcDZAiLQD
  MSOMqVB8Sjy1BwV0CGFxOpm8hEPa2RUMgF4Cp3AD9Jf0pSDYGUoPJYwogGx0AHArhvmYHd
  pCzPLl/FkEC5R7a/PdBUk2eb0A3Tu7IKLCZbuATJAAAFkNyKVAfcilQHAAAAB3NzaC1yc2
  EAAAGBAKLd3sUGO4NBKEKDSpmS3uEjIpLQ9KyWFaLinnf03bMgaaB9/q/ru95qyeJkEgg5
  OgRpKvhrxuid3Ug2PXGzg0QbsnaA6BqRXfj4OrOlHz9eJQDSwZdQq3NP1jQ3MbDYNDojJL
  jDqAM32bxUY0MSpMeI5H3y8udubGRl7JMxRXgThF731SgpQNp1GgD6p78tYn4feYnAHR+6
  zMUXQsZll3bcoocgsb5pycqk24jRsqg+GOWIFRmgI9+BpkH++7ww97e9OoL/fHJhkpl5/M
  VsplIBRMHQtdCD4OOWEB9aOe4WUboa9T+udSNCeGYniDt4Z6BqhynVsav4ljg1uPTMUsI/
  14KV1ZcvaH2LbH7Qchyqq9UgC839GjqbS9D0z/iixdBaxVVPD7QHA2QIi0AzEjjKlQfEo8
  tQcFdAhhcTqZvIRD2tkVDIBeAqdwA/SX9KUg2BlKDyWMKIBsdABwK4b5mB3aQszy5fxZBA
  uUe2vz3QVJNnm9AN07uyCiwmW7gEyQAAAAMBAAEAAAGBAIOtEkEFKvSRp3UvJQ9JGX24pG
  lDG661oUSSKEEf7ma2m++wLkwZMUk/2X16HsIbUnbieGVk7eqAR7nscH0O/9/+7Ki2y/E+
  +lUijINVyw+2lAA4ZWBrTlLqh2qr/TbXdlJSu4vOVHZVn2qOZ7qAxky0ttfFpvHJ60S4yy
  6uNVZBoVIO2X2g7NgyuRV1kk4U6X7C/8aJVoKiyo/GoKw60ty8wYKywkIK0aVO6FeUAvfX
  TNW20ihnutknvz24Y9rhUvwb7vO7Gbo+XNO3gkIpGM9eM0wN4IvfpypXWki8zCM+SIcqrz
  iePhwK2eBcHCg8+iqgpZFt7AMYTO4T7VbAGwv7fTBPcJPVY+sdDUg6OH8q8Ie8eUCIw1ua
  YCutrm14lmyjUbYlNFEWbZlJCBOENc4yNxOcQL3HMlpywbWqwnuRJxL1TzDZ/gyT+BaAAB
  YI6VBtiireUO0xoou5+0qxqdxm3AFuYpvRxBJfn+tGkQ5pKbg+saZ95hhOjH2RmYkMiQAA
  AMAzKV0Iny41GovZtU0XbwS8ymD5M5Prc8ufu0P0kEWWa3d43yu+LIGv1c+y1R4pr3ehTB
  wH5IrFMXVb82Ro+i7Jcmm1E2AQSGIB23kwn7+0cb4gBLIwBWYc0PGCGQ0p1CoTqsBocAap
  RrGWfsA9eoRp73AlNa8wd+184RgnjrXyavVBQHr4v64caFRoeKxwwzf2qWEdn93ANMuOb/
  VAzGab9nr8KFfM5WBbWDaXAhzrCzg6c3y2PnZks7bCbIVWEJ0AAADBANKE9v5ORbwUQMBg
  vYOQ0rrXDT9ztzIgClncOaGwmsMN2IXZqfJBkKH8clwDUnlTpIgSXl5/RWlLaKlpT2wblU
  ks9wnhIKw/G/6QguuMGBb1fHbU36+EIJjRpXdjAMPicNBBjWWKpDSL8tTpcU37B/9d0GMI
  aTSIMPK7/xxx6MtbkT7xZYCJA6QcWN2PhMOEYisB/2E1sonfYR39K+cG3kxCIhkAKrn/Pz
  Tz4ax2+ugpoLHPFRic5FRY/m7LB7mSnwAAAMEAxg1pxoaJATpbGtCInqyb18G3/H88tEkE
  tR6g/J5cNqVaK2Dtv9PPFy35E2YKgWMHLpgbkLwAl1dwTD7pPuDBlsPsz+G9yDrFr6DXon
  qWD5/ooeZ61oqop6UMN1qV0m+M6fFRjjwhuFftTOh159brza7gMX+Xn5/E29b/5h18fGq3
  F3NyfMMqDYI74qjbTlD9YJ1j6Hf50VSSO2uKpEZHA0kQpMd9m89FrpYf3IoGYrlcdDMkri
  +tttAKfhpPgdeXAAAAFXJkZXNvcm1lYXVAUkVORUFVRC1QQwECAwQF
  -----END OPENSSH PRIVATE KEY-----
  
  