artifactory-server: https://renodesorenterprise.jfrog.io/artifactory
artifactory-username: "renodesor@yahoo.fr"
artifactory-password: "D&sormeau1jf"
artifactory-api_key: da269b86-62ae-4987-92ab-a3863a400735
artifactory-access-token: eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJvYU1PcjJnUFUtNTFuMTRtNWZLQ1lpSUFUNlppaHFQbWtNLTRMemJuSU00In0.eyJzdWIiOiJqZmZlQDAxZ3Q3NWtlanA3a3JtMGZkZ2pka3ExeTN5XC91c2Vyc1wvcmVub2Rlc29yQHlhaG9vLmZyIiwic2NwIjoic3lzdGVtOmlkZW50aXRpZXM6cix3LGQiLCJhdWQiOiJqZmFjQCoiLCJpc3MiOiJqZmZlQDAxZ3Q3NWtlanA3a3JtMGZkZ2pka3ExeTN5IiwiaWF0IjoxNjc3NTQ5NjQxLCJqdGkiOiI2MTNkYzk1OC1jZGI0LTQxZTItOWEwYi1kMzcwNzliZDVjY2IifQ.a9G8tkkT0dc0v9LHVAzSCepVQhVU1qbL12pbyqKTKZeNuFnNqpkmkMzhVMFHBLuiwa9gI03jerjzsi2hMlyjPysQNt0vNLJ0hbdzqG1z0uCHdi5LXIshUz_nEAak2NgJphISyMKKjQK0B1pQMXICI2BDnKJqQyBoqUTwwJdTNRM71K5Wdb649MxwtAVT-EKLXUeeh1llhAV1Ekj2bGJjk2t--mwZ4WwDqe6oV0HhzVeT9xXDWGLFN3WfoDVfKcYScEiTivRuzxiMGyal5nUrIuIGGfwFlnqPq1xfi1gc_UWWeJZmH8whqVI0Z-O_B0gh2I1p7BTTOoHi7Ru8elOIUA

#BUILD_TEAM_NAME: main
#BUILD_PIPELINE_NUMBER: spring-security-auth
#BUILD_PIPELINE_NAME: spring-security-auth
#BUILD_JOB_NAME: build
#BUILD_NAME: 1.2.3
#BUILD_ID: 1.2.3
#COMPONENT_NAME: SpringSecurityAuth
#MAVEN_ADDITIONAL_ARGS: -Dpackage=war
PRODUCT_NAME: com/renodesor/multimodule
artifactId: gs-multi-module
git-repo-url: https://github.com/renodesor/gs-multi-module.git
  
  